#!/usr/bin/env python3
"""Generate the Board 1 BOM and audit documentation/data. Standard library only."""
import argparse
import csv
import json
import math
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
BOARD = ROOT / 'boards/board1'


def read_rows():
    with (BOARD / 'bom.csv').open(newline='') as stream:
        return list(csv.DictReader(stream))


def quantities(row, rules):
    if row['selection_status'] == 'superseded':
        return 0, 0, 'excluded'
    override = rules['overrides'].get(row['item_id'])
    if override:
        return override['purchase_quantity'], override['placement_quantity'], override['unit']
    return row['quantity'], row['quantity'], 'components; planning allocation'


def render_bom():
    rows = read_rows()
    rules = json.loads((BOARD / 'bom_quantity_rules.json').read_text())
    out = ['# Board 1 Rev A bill of materials', '',
           '<!-- Generated by scripts/board1_documents.py; edit bom.csv, bom_quantity_rules.json or bom_allocation_notes.md. -->', '',
           'Status: planning BOM; selected baseline through ADR-039. [CSV](bom.csv) owns parts and evidence. [Quantity rules](bom_quantity_rules.json) distinguish purchased source stock from placed pieces. Unknown counts stay TBD. All sourcing is through DigiKey; refresh order codes/stock before purchase. Acceptance is not electrical verification or an ordering release.', '']
    for status, title in [('accepted', 'Accepted selections'), ('proposed', 'Proposed residual networks'), ('superseded', 'Superseded; excluded from assembly and procurement')]:
        out += ['## ' + title, '', '| ID | Buy qty | Place qty | Function | MPN | Value / package | Quantity basis | Evidence | Authority |', '|---|---:|---:|---|---|---|---|---|---|']
        for row in rows:
            if row['selection_status'] != status:
                continue
            buy, place, unit = quantities(row, rules)
            cells = [row['item_id'], buy, place, row['function'], row['mpn'], row['value'] + '; ' + row['package'], unit, row['evidence_status'], row['adr']]
            out.append('| ' + ' | '.join(str(c).replace('|', '\\|').replace('\n', ' ') for c in cells) + ' |')
        out.append('')
    out += ['## Allocation and sourcing notes', '']
    out.append((BOARD / 'bom_allocation_notes.md').read_text().split('\n', 1)[1].strip())
    return '\n'.join(out) + '\n'


def usb_current(v, resistance, bridge_ma, load_ma, efficiency):
    """Low-current root of I=B+P/[eta*(V-RI)], returned in mA."""
    if not (v > 0 and resistance >= 0 and bridge_ma >= 0 and load_ma >= 0 and 0 < efficiency <= 1):
        raise ValueError('invalid power input')
    bridge = bridge_ma / 1000
    power = 3.3 * load_ma / 1000 / efficiency
    if resistance == 0:
        return 1000 * (bridge + power / v)
    a = v + resistance * bridge
    disc = a*a - 4*resistance*(v*bridge + power)
    if disc < 0:
        raise ValueError('no steady-state solution')
    return 1000 * 2*(v*bridge + power)/(a + math.sqrt(disc))


def main_load(s, t):
    can = t['can_phys']*s['can_idle'] + t['can_buses']*s['dominant_duty']*(s['can_dominant']-s['can_idle'])
    return (s['gw_3v3'] + 3*s['sam_each_3v3'] + s['misc_3v3'] + can + t['rs485_phys']*s['rs_each'] + s['led_count']*s['led_each_3v3'] + s['breakout_load_3v3'])


def audit():
    rows = read_rows()
    ids = [r['item_id'] for r in rows]
    assert len(ids) == len(set(ids)), 'duplicate BOM IDs'
    adr_files = list((ROOT / 'docs/decisions').glob('[0-9]*.md'))
    adr_ids = {f'ADR-{f.name[:3]}' for f in adr_files}
    for row in rows:
        assert None not in row and all(v for v in row.values()), row['item_id']
        assert row['selection_status'] in {'accepted', 'proposed', 'deferred', 'rejected', 'superseded'}
        assert row['evidence_status'] in {'unverified', 'verified'}
        assert row['assembly'] in {'fit', 'dnp', 'tbd'}
        assert row['quantity'] == 'TBD' or (row['quantity'].isdigit() and int(row['quantity']) >= 0)
        if row['selection_status'] == 'superseded':
            assert row['quantity'] == '0'
        assert set(re.findall(r'ADR-\d{3}', row['adr'])) <= adr_ids, row['item_id']
        if 'ADR-026' in row['adr']:
            assert '026-reva-connectors.md' in row['adr'] or '026-sam-core-ceramic.md' in row['adr']
        symbol = row['symbol'].split(':')[0]
        local = ROOT / 'libraries/symbols' / symbol
        if local.is_dir():
            assert list(local.glob('*.kicad_sym')), local
    rules = json.loads((BOARD / 'bom_quantity_rules.json').read_text())
    assert set(rules['overrides']) <= set(ids)
    by_id = {r['item_id']: r for r in rows}
    cuts = rules['header_cut']
    assert sum(c['pieces']*c['positions_each'] for c in cuts['cuts']) + cuts['spare_positions_unallocated'] == cuts['positions_per_strip']
    assert by_id['B1-B027']['mpn'] == by_id['B1-B059']['mpn'] == 'PRPC040SAAN-RC'
    assert quantities(by_id['B1-B027'], rules)[:2] == (1, 4)
    assert quantities(by_id['B1-B059'], rules)[:2] == (0, 4)
    assert quantities(by_id['B1-B011'], rules)[:2] == (0, 'TBD')
    assert by_id['B1-B075']['quantity'] == 'TBD', 'ground-pin count requires acceptance'
    assert (BOARD / 'BOM.md').read_text() == render_bom(), 'BOM.md is stale; run with --write'
    rendered_ids = re.findall(r'^\| (B1-B\d+) \|', render_bom(), re.M)
    assert len(rendered_ids) == len(ids) and set(rendered_ids) == set(ids)
    # Local file targets only: remote URLs and document fragments are separate evidence.
    for f in ROOT.rglob('*.md'):
        if '.git' in f.parts:
            continue
        for target in re.findall(r'\]\(([^)]+)\)', f.read_text()):
            if '://' in target or target.startswith('#'):
                continue
            dest = target.split('#')[0].strip('<>')
            assert (f.parent / dest).exists(), (f.relative_to(ROOT), target)
    duplicates = {}
    for f in adr_files:
        content = f.read_text()
        ident = re.search(r'^id: (ADR-\d+)$', content, re.M).group(1)
        duplicates.setdefault(ident, []).append(f.name)
        assert set(re.findall(r'ADR-\d{3}', content)) <= adr_ids, f.name
    assert {k: sorted(v) for k,v in duplicates.items() if len(v)>1} == {'ADR-026': ['026-reva-connectors.md','026-sam-core-ceramic.md']}
    data = json.loads((BOARD / 'power_budget.json').read_text())
    assert data['active_model'] == 'current_rev_a_input'
    m = data[data['active_model']]
    assert m['buck_mpn'] == by_id['B1-B012']['mpn']
    assert m['switch_mpn'] == by_id['B1-B044']['mpn']
    assert m['ct_nF'] == 47 and m['supervisor_fitted'] is False
    assert math.isclose(main_load(m['load_scenarios']['loaded_conservative'],m['topology']),m['main_load_conservative_mA'],abs_tol=1e-9)
    r = m['input_path_resistance_ohm_provisional']
    for result in m['results']:
        bridge = result['bridge_control_allowance_mA']
        calculated = usb_current(result['connector_V'],r,bridge,result['main_load_mA'],result['efficiency_assumption'])
        assert abs(calculated-result['usb_mA']) < 0.002, (calculated,result)
        assert abs(result['connector_V']-r*calculated/1000-result['buck_input_V']) < 0.0001
    limit = m['usb_configured_limit_mA'] / 1000
    eta = (3.3*m['main_load_conservative_mA']/1000)/((limit-m['bridge_control_allowance_mA']/1000)*(min(m['connector_V'])-r*limit))
    assert math.isclose(eta,m['efficiency_break_even'],abs_tol=1e-12)
    future = json.loads((BOARD / 'power_budget_future.json').read_text())
    for name, scenario in future['scenarios'].items():
        load = main_load(scenario,future['topology'])
        assert math.isclose(load,future['results'][name]['total_3v3'],abs_tol=1e-9)
        current = usb_current(scenario['vusb'],0,scenario['bridge_5v'],load,scenario['efficiency'])
        assert math.isclose(current,future['results'][name]['usb_input'],abs_tol=1e-9)
    print(f'PASS: {len(rows)} unique BOM rows, reproducible view, purchase/placement exclusions, ADR references/IDs, local file links, local symbol files, current and future power arithmetic.')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true', help='regenerate BOM.md before auditing')
    args = parser.parse_args()
    if args.write:
        (BOARD / 'BOM.md').write_text(render_bom())
    audit()
